version: "3"

services:
  springboot:
    image: "spring-agro-api"
    build: ./
    container_name: "Agro-API"
    restart: unless-stoped
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/api
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Europe/London
      - MYSQL_DATABASE=db_agro
    volumes:
      - path_to_data:/config
    ports:
      - 3306:3306
    restart: unless-stopped